/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Zhang
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public HomeForm() {
        initComponents();
        if (LogInForm.maQuyen == 0) {
            jbDKTaiKhoanSV.setVisible(false);
            jbThemMoiMH.setVisible(false);
            jbLapBangDiem.setVisible(false);
        } else {
            jbThongTinSinhVien.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTieuDe = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbDKTaiKhoanSV = new javax.swing.JButton();
        jbDSSinhVien = new javax.swing.JButton();
        jbThemMoiMH = new javax.swing.JButton();
        jbDSMonHoc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jbThoat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jbLapBangDiem = new javax.swing.JButton();
        jbDSDiemTB = new javax.swing.JButton();
        jbThongTinSinhVien = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTieuDe.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jlTieuDe.setText("STUDENT & SUBJECT MANAGEMENT SOFTWARE");
        jPanel1.add(jlTieuDe);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jbDKTaiKhoanSV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbDKTaiKhoanSV.setText("Sign up new student account");
        jbDKTaiKhoanSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDKTaiKhoanSVActionPerformed(evt);
            }
        });
        jPanel2.add(jbDKTaiKhoanSV, new java.awt.GridBagConstraints());

        jbDSSinhVien.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbDSSinhVien.setText("Student list");
        jbDSSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDSSinhVienActionPerformed(evt);
            }
        });
        jPanel2.add(jbDSSinhVien, new java.awt.GridBagConstraints());

        jbThemMoiMH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbThemMoiMH.setText("Add new subject");
        jbThemMoiMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThemMoiMHActionPerformed(evt);
            }
        });
        jPanel2.add(jbThemMoiMH, new java.awt.GridBagConstraints());

        jbDSMonHoc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbDSMonHoc.setText("Subject list");
        jbDSMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDSMonHocActionPerformed(evt);
            }
        });
        jPanel2.add(jbDSMonHoc, new java.awt.GridBagConstraints());

        jbThoat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbThoat.setText("Exit");
        jbThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThoatActionPerformed(evt);
            }
        });
        jPanel4.add(jbThoat);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jbLapBangDiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbLapBangDiem.setText("Create mark table");
        jbLapBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLapBangDiemActionPerformed(evt);
            }
        });
        jPanel8.add(jbLapBangDiem);

        jbDSDiemTB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbDSDiemTB.setText("Average marks list");
        jbDSDiemTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDSDiemTBActionPerformed(evt);
            }
        });
        jPanel8.add(jbDSDiemTB);

        jbThongTinSinhVien.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbThongTinSinhVien.setText("Student Information");
        jbThongTinSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThongTinSinhVienActionPerformed(evt);
            }
        });
        jPanel8.add(jbThongTinSinhVien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbDKTaiKhoanSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDKTaiKhoanSVActionPerformed
        // TODO add your handling code here:
        RegisterForm registerForm = new RegisterForm();
        registerForm.setVisible(true);
        registerForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbDKTaiKhoanSVActionPerformed

    private void jbThemMoiMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThemMoiMHActionPerformed
        // TODO add your handling code here:
        SubjectForm monHocForm = new SubjectForm();
        monHocForm.setVisible(true);
        monHocForm.setSize(600, 300);
        monHocForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbThemMoiMHActionPerformed

    private void jbLapBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLapBangDiemActionPerformed
        // TODO add your handling code here:
        MarksForm df = new MarksForm();
        df.setVisible(true);
        df.setSize(1000, 500);
        df.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbLapBangDiemActionPerformed

    private void jbDSDiemTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDSDiemTBActionPerformed
        // TODO add your handling code here:
        AverageMarksForm dsDiemTB = new AverageMarksForm();
        dsDiemTB.setVisible(true);
        dsDiemTB.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbDSDiemTBActionPerformed

    private void jbDSMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDSMonHocActionPerformed
        // TODO add your handling code here:
        SubjectListForm lmhf = new SubjectListForm();
        lmhf.setVisible(true);
        lmhf.setLocationRelativeTo(null);
        lmhf.hienThiDSMonHoc();
    }//GEN-LAST:event_jbDSMonHocActionPerformed

    private void jbDSSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDSSinhVienActionPerformed
        // TODO add your handling code here:
        StudentListForm svf = new StudentListForm();
        svf.setLocationRelativeTo(null);
        svf.setVisible(true);
        svf.hienThiDSSinhVien();
    }//GEN-LAST:event_jbDSSinhVienActionPerformed

    private void jbThongTinSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThongTinSinhVienActionPerformed
        // TODO add your handling code here:
        StudentInformationForm sif = new StudentInformationForm();
        sif.setVisible(true);
    }//GEN-LAST:event_jbThongTinSinhVienActionPerformed

    private void jbThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeForm trangChu = new HomeForm();
                trangChu.setVisible(true);
                trangChu.setLocationRelativeTo(null);
                trangChu.setSize(800, 400);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton jbDKTaiKhoanSV;
    private javax.swing.JButton jbDSDiemTB;
    private javax.swing.JButton jbDSMonHoc;
    private javax.swing.JButton jbDSSinhVien;
    private javax.swing.JButton jbLapBangDiem;
    private javax.swing.JButton jbThemMoiMH;
    private javax.swing.JButton jbThoat;
    private javax.swing.JButton jbThongTinSinhVien;
    private javax.swing.JLabel jlTieuDe;
    // End of variables declaration//GEN-END:variables
}
