/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Student;
import Model.StudentDAO;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author nhom4
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form DangKiForm1
     */
    public RegisterForm() {
        initComponents();
        hienThiDSKhoa();
        hienThiNamSinh();
        hienThiThangSinh();
        hienThiQuyenTruyCap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDangKy = new javax.swing.JButton();
        jbThoat = new javax.swing.JButton();
        jlTieuDe = new javax.swing.JLabel();
        jtfHoTen = new javax.swing.JTextField();
        jlMaSV = new javax.swing.JLabel();
        jlHoTen = new javax.swing.JLabel();
        jlMatKhau = new javax.swing.JLabel();
        jlNgaySinh = new javax.swing.JLabel();
        jlNoiSinh = new javax.swing.JLabel();
        jlKhoa = new javax.swing.JLabel();
        jtfMaSV = new javax.swing.JTextField();
        jtfNoiSinh = new javax.swing.JTextField();
        jtfLop = new javax.swing.JTextField();
        jlLop = new javax.swing.JLabel();
        jcbNgaySinh = new javax.swing.JComboBox<>();
        jcbThangSinh = new javax.swing.JComboBox<>();
        jcbNamSinh = new javax.swing.JComboBox<>();
        jcbKhoa = new javax.swing.JComboBox<>();
        jpfMatKhau = new javax.swing.JPasswordField();
        jlQuyenTruyCap = new javax.swing.JLabel();
        jcbQuyenTruyCap = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbDangKy.setText("Sign up");
        jbDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDangKyActionPerformed(evt);
            }
        });

        jbThoat.setText("Exit");
        jbThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThoatActionPerformed(evt);
            }
        });

        jlTieuDe.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jlTieuDe.setText("Sign up new student account");
        jlTieuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlTieuDe.setPreferredSize(new java.awt.Dimension(148, 50));

        jtfHoTen.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfHoTen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfHoTen.setHighlighter(null);
        jtfHoTen.setMargin(new java.awt.Insets(2, 10, 2, 20));
        jtfHoTen.setPreferredSize(new java.awt.Dimension(10, 10));

        jlMaSV.setBackground(new java.awt.Color(102, 255, 102));
        jlMaSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlMaSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMaSV.setText("Student ID");

        jlHoTen.setBackground(new java.awt.Color(102, 255, 102));
        jlHoTen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlHoTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHoTen.setText("Student full name");

        jlMatKhau.setBackground(new java.awt.Color(102, 255, 102));
        jlMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMatKhau.setText("Password");

        jlNgaySinh.setBackground(new java.awt.Color(102, 255, 102));
        jlNgaySinh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNgaySinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNgaySinh.setText("Birthday");

        jlNoiSinh.setBackground(new java.awt.Color(102, 255, 102));
        jlNoiSinh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNoiSinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNoiSinh.setText("Hometown");

        jlKhoa.setBackground(new java.awt.Color(102, 255, 102));
        jlKhoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlKhoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlKhoa.setText("Specializing");

        jtfMaSV.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfMaSV.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfMaSV.setHighlighter(null);
        jtfMaSV.setMargin(new java.awt.Insets(2, 10, 2, 20));
        jtfMaSV.setPreferredSize(new java.awt.Dimension(10, 10));

        jtfNoiSinh.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfNoiSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfNoiSinh.setHighlighter(null);
        jtfNoiSinh.setMargin(new java.awt.Insets(2, 10, 2, 20));
        jtfNoiSinh.setPreferredSize(new java.awt.Dimension(10, 10));

        jtfLop.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfLop.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfLop.setHighlighter(null);
        jtfLop.setMargin(new java.awt.Insets(2, 10, 2, 20));
        jtfLop.setPreferredSize(new java.awt.Dimension(10, 10));

        jlLop.setBackground(new java.awt.Color(102, 255, 102));
        jlLop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlLop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLop.setText("Class");

        jcbNgaySinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcbNgaySinhMouseEntered(evt);
            }
        });

        jcbThangSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbThangSinhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcbThangSinhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcbThangSinhMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcbThangSinhMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcbThangSinhMouseReleased(evt);
            }
        });

        jcbNamSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbNamSinhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcbNamSinhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcbNamSinhMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcbNamSinhMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcbNamSinhMouseReleased(evt);
            }
        });

        jlQuyenTruyCap.setBackground(new java.awt.Color(102, 255, 102));
        jlQuyenTruyCap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlQuyenTruyCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlQuyenTruyCap.setText("Access permission");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Day");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Year");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Month");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLop, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jbDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(jcbKhoa, 0, 394, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbThangSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(jtfLop, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(jtfNoiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                    .addComponent(jpfMatKhau)
                                    .addComponent(jcbQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbThangSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLop, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLop, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hienThiDSKhoa() {
        jcbKhoa.addItem("Ky thuat dien tu, truyen thong");
        jcbKhoa.addItem("Cong nghe ki thuat dien, dien tu");
        jcbKhoa.addItem("Cong nghe thong tin");
        jcbKhoa.addItem("An toan thong tin");
        jcbKhoa.addItem("Cong nghe da phuong tien");
        jcbKhoa.addItem("Quan tri kinh doanh");
        jcbKhoa.addItem("Marketing");
        jcbKhoa.addItem("Ke toan");
        jcbKhoa.addItem("Truyen thong da phuong tien");
    }

    public void hienThiQuyenTruyCap() {
        jcbQuyenTruyCap.addItem("Student");
        jcbQuyenTruyCap.addItem("Admin");
    }

    public void hienThiNamSinh() {
        GregorianCalendar gc = new GregorianCalendar();
        int year = gc.get(Calendar.YEAR);
        for (int i = 1980; i < year + 1; i++) {
            jcbNamSinh.addItem(i + "");
        }
    }

    public boolean kiemTraNamNhuan(int n) {
        if (n % 400 == 0 || (n % 4 == 0 && n % 100 != 0)) {
            return true;
        }
        return false;
    }

    public void hienThiThangSinh() {
        for (int i = 1; i < 13; i++) {
            jcbThangSinh.addItem(i + "");
        }
    }

    public void hienThiNgaySinh() {
        int nam = Integer.parseInt(jcbNamSinh.getSelectedItem().toString());
        int thang = Integer.parseInt(jcbThangSinh.getSelectedItem().toString());
        if (kiemTraNamNhuan(nam)) {
            if (thang == 2) {
                for (int i = 1; i < 30; i++) {
                    jcbNgaySinh.addItem(i + "");;
                }
                return;
            }
            if (thang == 1 || thang == 3 || thang == 5 || thang == 7 || thang == 8 || thang == 10 || thang == 12) {
                for (int i = 1; i < 32; i++) {
                    jcbNgaySinh.addItem(i + "");
                }
                return;
            } else {
                for (int i = 1; i < 31; i++) {
                    jcbNgaySinh.addItem(i + "");
                }
                return;
            }
        } else {
            if (thang == 2) {
                for (int i = 1; i < 29; i++) {
                    jcbNgaySinh.addItem(i + "");;
                }
                return;
            }
            if (thang == 1 || thang == 3 || thang == 5 || thang == 7 || thang == 8 || thang == 10 || thang == 12) {
                for (int i = 1; i < 32; i++) {
                    jcbNgaySinh.addItem(i + "");
                }
                return;
            } else {
                for (int i = 1; i < 31; i++) {
                    jcbNgaySinh.addItem(i + "");
                }
                return;
            }
        }

    }

    public String mauMaSV(String khoa) {
        String mau = "";
        if (khoa.equals("Ky thuat dien tu, truyen thong")) {
            mau = "[BC]\\d{2}((DC)|(CC)|(LC))(VT)\\d{3}";
            return mau;
        }
        if (khoa.equals("Cong nghe ki thuat dien, dien tu")) {
            mau = "[BC]\\d{2}((DC)|(CC)|(LC))(DT)\\d{3}";
            return mau;
        }
        if (khoa.equals("Cong nghe thong tin")) {
            mau = "[BC]\\d{2}((DC)|(CC)|(LC))(CN)\\d{3}";
            return mau;
        }
        if (khoa.equals("An toan thong tin")) {
            mau = "[BC]\\d{2}((DC)|(CC)|(LC))(AT)\\d{3}";
            return mau;
        }
        if (khoa.equals("Cong nghe da phuong tien")) {
            mau = "[BC]\\d{2}((DC)|(CC))(PT)\\d{3}";
            return mau;
        }
        if (khoa.equals("Quan tri kinh doanh")) {
            mau = "[BC]\\d{2}((DC)|(CC)|(LC))(QT)\\d{3}";
            return mau;
        }
        if (khoa.equals("Marketing")) {
            mau = "[BC]\\d{2}((DC)|(CC)|(LC))(MR)\\d{3}";
            return mau;
        }
        if (khoa.equals("Ke toan")) {
            mau = "[BC]\\d{2}((DC)|(CC)|(LC))(KT)\\d{3}";
            return mau;
        }
        if (khoa.equals("Truyen thong da phuong tien")) {
            mau = "[BC]\\d{2}((DC)|(CC)|(LC))(TT)\\d{3}";
            return mau;
        }
        return mau;
    }

    public String mauLop(String khoa) {
        String mau = "";
        if (khoa.equals("Ky thuat dien tu, truyen thong")) {
            mau = "[DC]\\d{2}(CQVT)\\d{2}\\-[BN]";
            return mau;
        }
        if (khoa.equals("Cong nghe ki thuat dien, dien tu")) {
            mau = "[DC]\\d{2}(CQDT)\\d{2}\\-[BN]";
            return mau;
        }
        if (khoa.equals("Cong nghe thong tin")) {
            mau = "[DC]\\d{2}(CQCN)\\d{2}\\-[BN]";
            return mau;
        }
        if (khoa.equals("An toan thong tin")) {
            mau = "[DC]\\d{2}(CQAT)\\d{2}\\-[BN]";
            return mau;
        }
        if (khoa.equals("Cong nghe da phuong tien")) {
            mau = "[DC]\\d{2}(CQTT)\\d{2}\\-[BN]";
            return mau;
        }
        if (khoa.equals("Quan tri kinh doanh")) {
            mau = "[DC]\\d{2}(CQQT)\\d{2}\\-[BN]";
            return mau;
        }
        if (khoa.equals("Marketing")) {
            mau = "[DC]\\d{2}(CQMR)\\d{2}\\-[BN]";
            return mau;
        }
        if (khoa.equals("Ke toan")) {
            mau = "[DC]\\d{2}(CQKT)\\d{2}\\-[BN]";
            return mau;
        }
        if (khoa.equals("Truyen thong da phuong tien")) {
            mau = "[DC]\\d{2}(CQTT)\\d{2}\\-[BN]";
            return mau;
        }
        return mau;
    }

    private void jbDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDangKyActionPerformed
        // TODO add your handling code here:
        String maSV = null, ten = null, mk = null, ngaySinh = null, noiSinh = null, lop = null, khoa = null, quyenTruyCapString = null;
        //-------------------------------------------------------
        khoa = jcbKhoa.getSelectedItem().toString();
        //-------------------------------------------------------
        try {
            maSV = jtfMaSV.getText();
            char charAt = maSV.charAt(0);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Student ID is empty");
            return;
        }
        //-------------------------------------------------------
        Student laySVTheoMa = new StudentDAO().laySVTheoMa(maSV);
        if (laySVTheoMa != null) {
            JOptionPane.showMessageDialog(this, maSV + " had account already . Log in to continue or try another student ID to register");
            return;
        }
        //-------------------------------------------------------
        try {
            ten = jtfHoTen.getText();
            char charAt = ten.charAt(0);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Student's name is empty");
            return;
        }
        //-------------------------------------------------------
        try {
            mk = jpfMatKhau.getText();
            char charAt = mk.charAt(0);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Password is empty");
            return;
        }
        //-------------------------------------------------------
        try {
            lop = jtfLop.getText();
            char charAt = lop.charAt(0);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Class is empty");
            return;
        }
        //-------------------------------------------------------
        try {
            noiSinh = jtfNoiSinh.getText();
            char charAt = noiSinh.charAt(0);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Hometown is empty");
            return;
        }
        //-------------------------------------------------------
        String mauMaSV = mauMaSV(khoa);
        if (!maSV.matches(mauMaSV)) {
            JOptionPane.showMessageDialog(this, "Illegal student ID (not match with specializing). Try again, for example B14DCCN123");
            return;
        }
        //-------------------------------------------------------
        if (ten.length() > 30) {
            JOptionPane.showMessageDialog(this, "Student name too long. Try again");
            return;
        }
        //-------------------------------------------------------
        if (mk.length() > 25) {
            JOptionPane.showMessageDialog(this, "Password cannot longer than 25 character");
            return;
        }
        //-------------------------------------------------------
        String namString = jcbNamSinh.getSelectedItem().toString();
        String thangString = jcbThangSinh.getSelectedItem().toString();
        String ngayString = null;
        Object selectedItem = jcbNgaySinh.getSelectedItem();
        if (selectedItem == null) {
            JOptionPane.showMessageDialog(this, "Please choose birthday");
            return;
        }
        ngayString = selectedItem.toString();
        int nam = Integer.parseInt(namString);
        int thang = Integer.parseInt(thangString);
        int ngay = Integer.parseInt(ngayString);
        ngaySinh = ngay + "/" + thang + "/" + nam;
        GregorianCalendar calendar = new GregorianCalendar();
        int year = calendar.get(Calendar.YEAR);
        if ((year - nam) < 18) {
            JOptionPane.showMessageDialog(this, "You're not enough to be student.");
            return;
        }
        //-------------------------------------------------------
        quyenTruyCapString = jcbQuyenTruyCap.getSelectedItem().toString();
        int quyen = 0;
        if (quyenTruyCapString.equals("Student")) {
            quyen = 0;
        } else {
            quyen = 1;
        }
        //-------------------------------------------------------
        String mauLop = mauLop(khoa);
        if (!lop.matches(mauLop)) {
            JOptionPane.showMessageDialog(this, "Illegal class (not match with specializing). Try again, for example D14CQCN01-B");
            return;
        }
        Student sinhVien = new Student(maSV, ten, mk, ngaySinh, noiSinh, lop, khoa, quyen);
        StudentDAO svDAO = new StudentDAO();
        if (svDAO.addSinhVien(sinhVien)) {
            JOptionPane.showMessageDialog(this, "Register succeded");
        } else {
            JOptionPane.showMessageDialog(this, "Register failed");
        }
    }//GEN-LAST:event_jbDangKyActionPerformed

    private void jbThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbThoatActionPerformed

    private void jcbNamSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbNamSinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNamSinhMouseClicked

    private void jcbNamSinhMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbNamSinhMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNamSinhMouseReleased

    private void jcbThangSinhMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbThangSinhMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbThangSinhMouseReleased

    private void jcbNamSinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbNamSinhMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNamSinhMouseExited

    private void jcbThangSinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbThangSinhMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbThangSinhMouseExited

    private void jcbNamSinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbNamSinhMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNamSinhMouseEntered

    private void jcbNamSinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbNamSinhMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNamSinhMousePressed

    private void jcbThangSinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbThangSinhMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbThangSinhMouseEntered

    private void jcbNgaySinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbNgaySinhMouseEntered
        // TODO add your handling code here:
        hienThiNgaySinh();
    }//GEN-LAST:event_jcbNgaySinhMouseEntered

    private void jcbThangSinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbThangSinhMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbThangSinhMousePressed

    private void jcbThangSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbThangSinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbThangSinhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbDangKy;
    private javax.swing.JButton jbThoat;
    private javax.swing.JComboBox<String> jcbKhoa;
    private javax.swing.JComboBox<String> jcbNamSinh;
    private javax.swing.JComboBox<String> jcbNgaySinh;
    private javax.swing.JComboBox<String> jcbQuyenTruyCap;
    private javax.swing.JComboBox<String> jcbThangSinh;
    private javax.swing.JLabel jlHoTen;
    private javax.swing.JLabel jlKhoa;
    private javax.swing.JLabel jlLop;
    private javax.swing.JLabel jlMaSV;
    private javax.swing.JLabel jlMatKhau;
    private javax.swing.JLabel jlNgaySinh;
    private javax.swing.JLabel jlNoiSinh;
    private javax.swing.JLabel jlQuyenTruyCap;
    private javax.swing.JLabel jlTieuDe;
    private javax.swing.JPasswordField jpfMatKhau;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfLop;
    private javax.swing.JTextField jtfMaSV;
    private javax.swing.JTextField jtfNoiSinh;
    // End of variables declaration//GEN-END:variables
}
