/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.MarksDAO;
import Model.TempMarks;
import Model.Student;
import Model.StudentDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zhang
 */
public class StudentInformationForm extends javax.swing.JFrame {

    ArrayList<TempMarks> dsDiem;
    String maLayDuoc = LogInForm.maSinhVien;

    /**
     * Creates new form StudentInformationForm
     */
    public StudentInformationForm() {
        initComponents();
        hienThiThongTinCaNhan();
        hienThiDSDiem();
        hienThiDiemTrungBinh();
    }

    public void hienThiThongTinCaNhan() {
        Student sinhVien = new StudentDAO().laySVTheoMa(maLayDuoc);
        jlThongTinMaSV.setText(sinhVien.getMaSV());
        jlThongTinTenSV.setText(sinhVien.getTenSV());
        jlThongTinMatKhau.setText(sinhVien.getMatKhau());
        jlThongTinNgaySinh.setText(sinhVien.getNgaySinh());
        jlThongTinNoiSinh.setText(sinhVien.getNoiSinh());
        jlThongTinLop.setText(sinhVien.getLop());
        jlThongTinKhoa.setText(sinhVien.getKhoa());
    }

    public void hienThiDSDiem() {
        dsDiem = new MarksDAO().LayDanhSachChiTietDiemTheoMa(maLayDuoc);
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Subject ID");
        dtm.addColumn("Subject's name");
        dtm.addColumn("Marks");
        for (int i = 0; i < dsDiem.size(); i++) {
            String[] data = {dsDiem.get(i).getMonHoc().getMaMon(), dsDiem.get(i).getMonHoc().getTenMon(), dsDiem.get(i).getDiem() + ""};
            dtm.addRow(data);
        }
        jtBangDiem.setModel(dtm);
    }

    public void hienThiDiemTrungBinh() {
        float diemTB = 0;
        for (int i = 0; i < dsDiem.size(); i++) {
            diemTB += dsDiem.get(i).getDiem();
        }
        diemTB /= dsDiem.size();
        jlThongTinDiemTB.setText(diemTB + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTieuDe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlMaSV = new javax.swing.JLabel();
        jlTenSV = new javax.swing.JLabel();
        jlMatKhau = new javax.swing.JLabel();
        jlNgaySinh = new javax.swing.JLabel();
        jlNoiSinh = new javax.swing.JLabel();
        jlLop = new javax.swing.JLabel();
        jlKhoa = new javax.swing.JLabel();
        jlThongTinMaSV = new javax.swing.JLabel();
        jlThongTinTenSV = new javax.swing.JLabel();
        jlThongTinMatKhau = new javax.swing.JLabel();
        jlThongTinNgaySinh = new javax.swing.JLabel();
        jlThongTinNoiSinh = new javax.swing.JLabel();
        jlThongTinLop = new javax.swing.JLabel();
        jlThongTinKhoa = new javax.swing.JLabel();
        jlTieuDeBangDiem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBangDiem = new javax.swing.JTable();
        jlDiemTB = new javax.swing.JLabel();
        jlThongTinDiemTB = new javax.swing.JLabel();
        jbThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlTieuDe.setText("Personal Information");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlMaSV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlMaSV.setText("Student ID");

        jlTenSV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTenSV.setText("Student's name");

        jlMatKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlMatKhau.setText("Password");

        jlNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNgaySinh.setText("Birthday");

        jlNoiSinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNoiSinh.setText("Hometown");

        jlLop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlLop.setText("Class");

        jlKhoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlKhoa.setText("Specializing");

        jlThongTinMaSV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlThongTinMaSV.setText("jLabel12");

        jlThongTinTenSV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlThongTinTenSV.setText("jLabel12");

        jlThongTinMatKhau.setText("jLabel12");

        jlThongTinNgaySinh.setText("jLabel12");

        jlThongTinNoiSinh.setText("jLabel12");

        jlThongTinLop.setText("jLabel12");

        jlThongTinKhoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlThongTinKhoa.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMaSV)
                    .addComponent(jlTenSV)
                    .addComponent(jlMatKhau)
                    .addComponent(jlNgaySinh)
                    .addComponent(jlNoiSinh)
                    .addComponent(jlLop)
                    .addComponent(jlKhoa))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlThongTinKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlThongTinLop, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlThongTinNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlThongTinNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlThongTinMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlThongTinTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlThongTinMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMaSV)
                    .addComponent(jlThongTinMaSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTenSV)
                    .addComponent(jlThongTinTenSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMatKhau)
                    .addComponent(jlThongTinMatKhau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNgaySinh)
                    .addComponent(jlThongTinNgaySinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNoiSinh)
                    .addComponent(jlThongTinNoiSinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLop)
                    .addComponent(jlThongTinLop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlKhoa)
                    .addComponent(jlThongTinKhoa))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jlTieuDeBangDiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTieuDeBangDiem.setText("Subject and marks list");

        jtBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject ID", "Subject's name", "Marks"
            }
        ));
        jtBangDiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBangDiemKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtBangDiem);

        jlDiemTB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlDiemTB.setText("Average marks: ");

        jlThongTinDiemTB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlThongTinDiemTB.setText("..........");

        jbThoat.setText("Exit");
        jbThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlDiemTB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlThongTinDiemTB)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jlTieuDe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jlTieuDeBangDiem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlTieuDeBangDiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDiemTB)
                    .addComponent(jlThongTinDiemTB))
                .addGap(18, 18, 18)
                .addComponent(jbThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThoatActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jbThoatActionPerformed

    private void jtBangDiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBangDiemKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JOptionPane.showMessageDialog(this, "Cannot change any thing in this table");
            hienThiDSDiem();
        }
    }//GEN-LAST:event_jtBangDiemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInformationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInformationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInformationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInformationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbThoat;
    private javax.swing.JLabel jlDiemTB;
    private javax.swing.JLabel jlKhoa;
    private javax.swing.JLabel jlLop;
    private javax.swing.JLabel jlMaSV;
    private javax.swing.JLabel jlMatKhau;
    private javax.swing.JLabel jlNgaySinh;
    private javax.swing.JLabel jlNoiSinh;
    private javax.swing.JLabel jlTenSV;
    private javax.swing.JLabel jlThongTinDiemTB;
    private javax.swing.JLabel jlThongTinKhoa;
    private javax.swing.JLabel jlThongTinLop;
    private javax.swing.JLabel jlThongTinMaSV;
    private javax.swing.JLabel jlThongTinMatKhau;
    private javax.swing.JLabel jlThongTinNgaySinh;
    private javax.swing.JLabel jlThongTinNoiSinh;
    private javax.swing.JLabel jlThongTinTenSV;
    private javax.swing.JLabel jlTieuDe;
    private javax.swing.JLabel jlTieuDeBangDiem;
    private javax.swing.JTable jtBangDiem;
    // End of variables declaration//GEN-END:variables
}
