/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Subject;
import Model.SubjectDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nhom4
 */
public class SubjectForm extends javax.swing.JFrame {

    /**
     * Creates new form MonHocForm
     */
    public SubjectForm() {
        initComponents();
        hienThiDSKhoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlThongTinMH = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbThem = new javax.swing.JButton();
        jbThoat = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jlMaMH = new javax.swing.JLabel();
        jtfMaMonHoc = new javax.swing.JTextField();
        jlTenMon = new javax.swing.JLabel();
        jtfTenMonHoc = new javax.swing.JTextField();
        jlSoTinChi = new javax.swing.JLabel();
        jtfSoTinChi = new javax.swing.JTextField();
        jlKhoa = new javax.swing.JLabel();
        jcbKhoa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Mã môn học");
        jPanel1.add(jLabel2);

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel1.add(jTextField4);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Tên môn");
        jPanel1.add(jLabel1);

        jTextField1.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanel1.add(jTextField1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Số tính chỉ");
        jPanel1.add(jLabel3);

        jTextField2.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanel1.add(jTextField2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Khoa");
        jPanel1.add(jLabel4);

        jTextField3.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanel1.add(jTextField3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(150, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(452, 50));

        jlThongTinMH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlThongTinMH.setText("Subject information");
        jPanel2.add(jlThongTinMH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 50));

        jbThem.setText("Add");
        jbThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThemActionPerformed(evt);
            }
        });
        jPanel3.add(jbThem);

        jbThoat.setText("Exit");
        jbThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThoatActionPerformed(evt);
            }
        });
        jPanel3.add(jbThoat);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.GridLayout(4, 0, 10, 10));

        jlMaMH.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlMaMH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMaMH.setText("Subject ID");
        jlMaMH.setAlignmentX(10.0F);
        jlMaMH.setFocusTraversalPolicyProvider(true);
        jlMaMH.setFocusable(false);
        jlMaMH.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jlMaMH.setMinimumSize(new java.awt.Dimension(59, 5));
        jlMaMH.setPreferredSize(new java.awt.Dimension(5, 5));
        jPanel5.add(jlMaMH);

        jtfMaMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfMaMonHoc.setMinimumSize(new java.awt.Dimension(200, 50));
        jtfMaMonHoc.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(jtfMaMonHoc);

        jlTenMon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlTenMon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTenMon.setText("Subject's name");
        jlTenMon.setFocusable(false);
        jlTenMon.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel5.add(jlTenMon);

        jtfTenMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfTenMonHoc.setMinimumSize(new java.awt.Dimension(200, 50));
        jtfTenMonHoc.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(jtfTenMonHoc);

        jlSoTinChi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSoTinChi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSoTinChi.setText("Number of credits");
        jlSoTinChi.setFocusable(false);
        jlSoTinChi.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel5.add(jlSoTinChi);

        jtfSoTinChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfSoTinChi.setMinimumSize(new java.awt.Dimension(200, 50));
        jtfSoTinChi.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(jtfSoTinChi);

        jlKhoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlKhoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlKhoa.setText("Specializing");
        jlKhoa.setFocusable(false);
        jlKhoa.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel5.add(jlKhoa);

        jcbKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbKhoaActionPerformed(evt);
            }
        });
        jPanel5.add(jcbKhoa);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hienThiDSKhoa() {
        jcbKhoa.addItem("Co ban");
        jcbKhoa.addItem("Ky thuat dien tu, truyen thong");
        jcbKhoa.addItem("Cong nghe ki thuat dien, dien tu");
        jcbKhoa.addItem("Cong nghe thong tin");
        jcbKhoa.addItem("An toan thong tin");
        jcbKhoa.addItem("Cong nghe da phuong tien");
        jcbKhoa.addItem("Quan tri kinh doanh");
        jcbKhoa.addItem("Marketing");
        jcbKhoa.addItem("Ke toan");
        jcbKhoa.addItem("Truyen thong da phuong tien");
    }

    private void jbThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThemActionPerformed
        // TODO add your handling code here:
        String maMon = null, tenMon = null, khoa = null, soTinChiTemp = null;
        int soTinChi = 0;
        try {
            maMon = jtfMaMonHoc.getText();
            char charAt = maMon.charAt(0);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Subject ID is empty");
            return;
        }
        try {
            tenMon = jtfTenMonHoc.getText();
            char charAt = tenMon.charAt(0);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Subject's name is empty");
            return;
        }
        try {
            soTinChiTemp = jtfSoTinChi.getText();
            char charAt = soTinChiTemp.charAt(0);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Number of credits is empty");
            return;
        }
        khoa = jcbKhoa.getSelectedItem().toString();
        String mauMaMH = "((BAS)|(INT)|(ELE)|(TEL)|(SKD)|(CDT)|(FIA)|(BSA)|(EPT)|(CDIT))\\d{4}";
        if (!maMon.matches(mauMaMH)) {
            JOptionPane.showMessageDialog(this, "Subject ID is incorrect.");
            return;
        }
        if (tenMon.length() > 50) {
            JOptionPane.showMessageDialog(this, "Length of subject's name is not over 50 character");
            return;
        }
        try {
            soTinChi = Integer.parseInt(soTinChiTemp);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Number of credits must be a NUMBER. Please enter exactly");
            return;
        }
        if (soTinChi < 0 || soTinChi > 10) {
            JOptionPane.showMessageDialog(this, "The number of credits must be under 11 and over 0");
            return;
        }
        ArrayList<Subject> dsMonHoc = new SubjectDAO().layDanhSachMonHoc();
        for (int i = 0; i < dsMonHoc.size(); i++) {
            if (dsMonHoc.get(i).getMaMon().equals(maMon)) {
                JOptionPane.showMessageDialog(this, "This subject already had. Try again.");
                return;
            }
        }
        Subject monHoc = new Subject(maMon, tenMon, khoa, soTinChi);
        SubjectDAO mhDAO = new SubjectDAO();
        if (mhDAO.addMonHoc(monHoc)) {
            JOptionPane.showMessageDialog(this, "Adding succeeded");
        } else {
            JOptionPane.showMessageDialog(this, "Adding failed");
        }
    }//GEN-LAST:event_jbThemActionPerformed

    private void jbThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbThoatActionPerformed

    private void jcbKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbKhoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SubjectForm subjectForm = new SubjectForm();
            subjectForm.setVisible(true);
            subjectForm.setSize(600, 300);
            subjectForm.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbThem;
    private javax.swing.JButton jbThoat;
    private javax.swing.JComboBox<String> jcbKhoa;
    private javax.swing.JLabel jlKhoa;
    private javax.swing.JLabel jlMaMH;
    private javax.swing.JLabel jlSoTinChi;
    private javax.swing.JLabel jlTenMon;
    private javax.swing.JLabel jlThongTinMH;
    private javax.swing.JTextField jtfMaMonHoc;
    private javax.swing.JTextField jtfSoTinChi;
    private javax.swing.JTextField jtfTenMonHoc;
    // End of variables declaration//GEN-END:variables
}
